### ISSUE TITLE
Things to check before the release of COMOKIT V1

### ISSUE THREAD

**Issue by AlexisDrogoul** [COMOKIT/COMOKIT-Model#20]
Hi,

Here are all the things to check before the release of COMOKIT V1. Please

- **tick** where you think it has been done, 
- **edit** this issue to add new requirements
- **comment** to indicate that you are working on a specific task. 

### Build
- [x] As soon as the code is considered as frozen, create a tag called `v1.0` and make sure it is correctly displayed in the [releases](https://github.com/COMOKIT/COMOKIT-Model/releases), as well as accessible by https://github.com/COMOKIT/COMOKIT-Model/releases/tag/v1.0
### Model
- [x] Verify that all the experiments are working on all the datasets shipped by default
- [x] Make sure that the code is properly commented
- [x] Make sure that the purpose of each experiment is explained (it is a bit hard, sometimes, to understand what they are meant to !) (see last commit here : https://github.com/COMOKIT/COMOKIT-Model/commit/4560be9036fa27f3e1a6115216a355b96e67e33b)
- [x] Make sure that no `write` or debug information are left over (https://github.com/COMOKIT/COMOKIT-Model/commit/2cc6aa2faed14c1156a7ee2d995e0887f9047ff4)
- [x] Verify all headers (and put http://comokit.org instead of the old address) + a mention to V1 and the date (May 2020) (077aca52c1ea66754de51827bcf75274fbaf6fb4)
- [x] Build an asset that contains GAMA + JDK + COMOKIT (with COMOKIT V1 and the template project in the Library of Models or in a specific plugin of GAMA ?) and have it available to download ? (3a0bd882758f0738cdc12f3e6642f38edf2f7f88, fba3d567f939ec476d2169a7814cf50d5b4c098a, 16c29c4b21b04be1abecc86564e3e97d7aa261de)
  - Saved in Library Models
  - https://github.com/COMOKIT/COMOKIT-Model/releases
- [x] Have a more complete [README.md](https://github.com/COMOKIT/COMOKIT-Model/blob/master/README.md) file or description of the release, so as to not force people to go to the website to know how to run it. (b0c78e7c4ce1b40d39bc274175ce30005b1d6583, fb0cb74cbffd3dc34f43e183f0e415691b67f241, 8436fe5e6dd58b709c7c1d02d86b8b4293cdb085, 02f049013e9c2c78dd792ddbcc7bcebb84af5cfc)

### Templates
- [x] Add 2-3 more templates (comparison between policies, for instance) to the template project
- [x] Document the use of the template project (in the code and README.md ?)
- [x] Verify the headers (see above)

### Website
- [x] Have a functional [website](https://comokit.github.io/COMOKIT-Website/)
- [x] Reuse, for the site, material from the [Covid19 page](https://gama-platform.github.io/covid19) and shut down this page once it is done
- [x] Prepare a small introductory text for V1, publish it on the website on a dedicated page (see https://comokit.org/docs/version1)
- [x] Have a section on it dedicated to the documentation and guidelines (see below)

### Documentation & guidelines
- [x] Make sure that the [ODD description](https://docs.google.com/document/d/1QFIe0mA0TikVWB95mzxLe7huX11HhFOBXQH-Dap_o9c/edit#heading=h.r5367ieg4wb2)  is on par with the model 
- [x] Publish the ODD description on the website (as a PDF and/or HTML version)
- [x] Make a [simplified version of the ODD description](https://docs.google.com/document/d/1K52MEQ0kxSXyA1HdruQN6Uun_oe3_rLEuq-Z8pFHj7g/edit#heading=h.r5367ieg4wb2) to describe the model ([b892ee9](https://github.com/COMOKIT/COMOKIT-Website/commit/b892ee9942c6bcfa1a5c631c8d8d72542566ace1))
- [x] Write a A to Z documentation on how to use COMOKIT on a specific dataset (what to download, duplicate the template project, things to check, etc.)

### COMSES & others
- [x] Prepare the submission to the [COMSES library](https://www.comses.net/codebases/add/)
see https://www.comses.net/codebases/7d686bf0-ff0a-46c0-b4a6-d341ef9e13c2/releases/1.0.0/
- [x] Similarly add a mention to it from [ResearchGate](https://www.researchgate.net/project/COMOKIT) and [OSF](https://osf.io/5hn9d/)

### Social Media & others
- [x] Share the release of V1 on GAMA FB page using the text of the website 
- [x] Share the release of V1 on GAMA Mailing-list, JASSS mailing-list, others ? 
- [x] Share the release of V1 on LinkedIn (personal accounts).

### Other
- [x]  Create a contact@comokit.org mail address (done, redirects by default to @AlexisDrogoul, @ptaillandier, @benoitgaudou, @chapuisk, @RoiArthurB, @hqnghi88 and @DAM-Philippon on their gmail address with the `+comokit` extension to easily filter it).

**Comment by chapuisk** [comment]
@AlexisDrogoul for the "Make sure that no write or debug information are left over" is it only a mater of deleting all writing statement or do we add a DEBUG / VERBOSE variable to allow console output ?

**Comment by RoiArthurB** [comment]
Does anyone know where to put the Template folder in the All-In-One archive for it to be well integrated within GAMA ? 🤔🤔🤔

**Comment by benoitgaudou** [comment]
Note: on PartialPolicy: some Individuals are allowed to go to work but not to go back home.
(in fact, this policy allows randomly Individuals to do their activity).

In contrarily, the policy `AllowedIndividualsPolicy` chose some Individuals at the beginning and always allows their activities.

**Comment by RoiArthurB** [comment]
Release V1.0 in draft here : https://github.com/COMOKIT/COMOKIT-Model/releases/tag/untagged-492979c66c9a4e275f3f

**Comment by AlexisDrogoul** [comment]
Done ! Thanks to all who contributed !
