### ISSUE TITLE
The Realistic Lockdown Duration.gaml is raising a java.util.ConcurrentModificationException at init

### ISSUE THREAD

**Issue by chapuisk** [COMOKIT/COMOKIT-Model#24]
Although an error is raised the simulation actually run. The visualization of the ground image is not possible and seems only to impact initialization phase !
At might come from the fact that simulation are created within a loop statement...

**Comment by chapuisk** [comment]
The fact that ``Tolerance in Partial Lockdown.gaml`` has the same behavior goes for the creation-in-loop thing

**Comment by AlexisDrogoul** [comment]
I cant reproduce this bug with the latest version of both GAMA and COMOKIT. And even if I tell GAMA to report errors in displays, as it seems to be linked (?). What did the error tell ? Where was it happening ?

**Comment by chapuisk** [comment]
The error did not shows up this morning ...
