### ISSUE TITLE
lot of errors when loading on mac 10.15.

### ISSUE THREAD

**Issue by chrisdie** [COMOKIT/COMOKIT-Model#25]
I get a lot of errors when importing the current COVID model in Gama 1.8.0 on Mac Cataling 10.15

What am I doing wrong?

<img width="1336" alt="Bildschirmfoto 2020-05-07 um 13 21 08" src="https://user-images.githubusercontent.com/15226303/81289032-f8e3d980-9065-11ea-90f1-4707878f3990.png">

**Comment by benoitgaudou** [comment]
First of all, you will need to download the GAMA continuous built version : 
https://github.com/gama-platform/gama/releases/tag/continuous

**Comment by chrisdie** [comment]
yes, thanks - that was it
