### ISSUE TITLE
School and workplace shutdown.gaml: no infection

### ISSUE THREAD

**Issue by benoitgaudou** [COMOKIT/COMOKIT-Model#29]
I run the experiment `School and workplace shutdown.gaml` with no closure (so set in the user_input popup, both closures to false).

So we can observe individuals moving both to schools and working places.

But, even after running the experiment several times (3 or 4 times), I cannot observe that the disease spreads in the population (basically, only the 2 initial infected people are infected all over the simulations)

**Comment by chapuisk** [comment]
There is no more spread at all !!!

<img width="1680" alt="Screen Shot 2020-05-10 at 17 07 58" src="https://user-images.githubusercontent.com/13599506/81502852-d90c1a00-92e0-11ea-9831-a47c78fed48e.png">

**Comment by chapuisk** [comment]
It is because of bool casting in reading Epidemiological Parameters.csv variable allow_transmission_human and allow_transmission_building: value in the file was TRUE and the Gama cast bool(TRUE) seems to return false ...

**Comment by AlexisDrogoul** [comment]
Yes. Only `bool("true")` (i.e. the exact serialisation of `true`) returns `true`. All the other strings return `false`.

**Comment by chapuisk** [comment]
@AlexisDrogoul I change the value in the file ! Do we consider that COMOKIT should be more permissive or not: if we stick to gaml's requirement, we can close the issue, see 64527ccb
