### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by shianli** [COMOKIT/COMOKIT-Model#37]
GAMA is trying to look for Building type per activity type.csv (in Parameters folder) in the application model folder instead of COMOKIT folder when the application model is launch outside COMOKIT

**Comment by chapuisk** [comment]
In order to reproduce the error, create a new model in COMOKIT Template Project based on any template and point dataset variable toward a usable dataset, e.g. ``string dataset_path <- "../../COMOKIT/Datasets/Sample/";``

**Comment by AlexisDrogoul** [comment]
I seem to remember that this file had been added by @ptaillandier , no ?

**Comment by ptaillandier** [comment]
It has been added in the Parameters folder.....

**Comment by chapuisk** [comment]
add a parameter_folder_path var to specify parameter folder and add it to COMOKIT Template Projects, see 913a7dafca634dd487b6dfaa38eee224ca1926e0

**Comment by AlexisDrogoul** [comment]
I would suggest to call it `parameters_path` or `parameters_folder_path` (with an "s").
