### ISSUE TITLE
[GHA] Switch pre-release on GAMA 1.8.2

### ISSUE THREAD

**Issue by RoiArthurB** [COMOKIT/COMOKIT-Model#48]
**Describe the bug**
The current pre-release of COMOKIT All-in-one is using the stable GAMA 1.8.1. To prepare the switch on GAMA 1.8.2 it would be great to switch the pre-release on that new version of GAMA.

**Expected behavior**
Changing the GitHub Action creating the pre-release to get the latest pre-release of GAMA 1.8.2 and make a regular pre-release with it.

**Comment by ndgnuh** [comment]
Can this issue be closed after #49? Or there is something else?

**Comment by RoiArthurB** [comment]
Sure totally forgot to close it ! 🙈🙈🙈
